// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5QH-6wctFJpnt6xc0_kLHpab5QcX3PMw',
    appId: '1:221575439519:web:5076d40b0695d706672eaa',
    messagingSenderId: '221575439519',
    projectId: 'cdrotas2',
    authDomain: 'cdrotas2.firebaseapp.com',
    storageBucket: 'cdrotas.appspot.com',
    measurementId: 'G-6Z4E4RD12R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAfr1Ha4X50lZXC9LCc-1g2IqH66BOmkc',
    appId: '1:221575439519:android:e76a1fd415f311ff672eaa',
    messagingSenderId: '221575439519',
    projectId: 'cdrotas2',
    storageBucket: 'cdrotas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUaaiyA7GjZMGMlWkW5NiBE3ee7d7D7ig',
    appId: '1:221575439519:ios:f3d71c36bead5ac1672eaa',
    messagingSenderId: '221575439519',
    projectId: 'cdrotas2',
    storageBucket: 'cdrotas.appspot.com',
    iosClientId:
        '221575439519-lgjnpup4emothhl01s7ou5lsgvbmldkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuapp',
  );
}
